hQuery.php: duzun\hQuery\Context Class Reference
duzun\hQuery\Context Class Reference
Public Member Functions
__construct ($doc=NULL, $el_arr=NULL)
intersect ($el, $eq=true)
Public Member Functions inherited from duzun\hQuery\Node
attr ($attr=NULL, $to_str=false)
is_empty ()
isEmpty ()
isDoc ()
doc ()
find ($sel, $attr=NULL)
exclude ($sel, $attr=NULL)
__toString ()
html ($id=NULL)
outerHtml ($id=NULL)
text ($id=NULL)
nodeName ($caseFolding=NULL, $id=NULL)
pos ($restore=true)
_children ($ids=NULL, $n=NULL)
_next ($ids=NULL, $n=0)
_prev ($ids=NULL, $n=0)
_all ($ids=NULL)
_has ($el, $eq=false)
$el < $this, with $eq == true -> $el <= $this
_filter_contains ($el, $eq=false)
__get ($name)
__set ($name, $value)
__isset ($name)
__unset ($name)
count ()
current ()
valid ()
key ()
next ()
prev ()
rewind ()
Additional Inherited Members
Static Public Member Functions inherited from duzun\hQuery\Node
static html_normal_pseudoClass ($p)
static html_selector2struc ($sel)
static html_parseAttrStr ($str, $case_folding=true, $extended=false)
static html_attr2str ($attr, $quote='"')
static parseCSStr ($str, $case_folding=true)
static CSSArr2Str ($css)
static str_range ($comp, $pos=0, $len=NULL)
static array_select ($arr, $keys, $force_null=false)
static convert_encoding ($a, $to, $from=NULL)
Public Attributes inherited from duzun\hQuery\Node
const VERSION = '2.0.2'
$tag_map
Static Public Attributes inherited from duzun\hQuery\Node
static $last_http_result
static $selected_doc = NULL
static $_ar_ = array()
static $_mi_ = PHP_INT_MAX
static $_nl_ = NULL
static $_fl_ = false
static $_tr_ = true
Protected Member Functions inherited from duzun\hQuery\Node
__construct ($doc, $ids, $is_ctx=false)
_ctx_ids ($ids=NULL)
_sub_ids ($eq=false)
_doc_ids ($el, $force_array=true)
_my_ids ($id=NULL, $keys=false)
_parent ($ids=NULL, $n=0)
Static Protected Member Functions inherited from duzun\hQuery\Node
static html_findTagClose ($str, $p)
Protected Attributes inherited from duzun\hQuery\Node
$_prop = array()
$doc
$ids
$exc
Detailed Description
A context is a list of node addresses with reference to their document.
API Documentation at https://duzun.github.io/hQuery.php
MIT
Definition at line 16 of file Context.php.
Member Function Documentation
intersect()
duzun\hQuery\Context::intersect ($el, $eq = true)
ctx($el) * $this
Returns
hQuery_Context ctx
Definition at line 34 of file Context.php.
References duzun\hQuery\Node\_ctx_ids(), duzun\hQuery\Node\_doc_ids(), and duzun\hQuery\Node\_has().
The documentation for this class was generated from the following file:
src/hQuery/Context.php